package util

// FillerPhrases is a list of common filler phrases sorted longest-first for greedy matching.
// These phrases add length but little information to memory content.
var FillerPhrases = []string{
	"after a long discussion about this",
	"after discussing this for a while",
	"it is worth noting that",
	"it is important to note that",
	"it turns out that",
	"as you may already know",
	"as you probably know",
	"as you may know",
	"as you know",
	"we spent some time on",
	"we spent time on",
	"we spent time",
	"after discussing",
	"after talking about",
	"after looking at",
	"eventually we decided",
	"eventually we",
	"at the end of the day",
	"at the end of",
	"in order to",
	"in terms of",
	"in the context of",
	"in the case of",
	"in the sense that",
	"for the purposes of",
	"for the most part",
	"for what it's worth",
	"needless to say",
	"it goes without saying",
	"it should be noted that",
	"it is worth mentioning that",
	"it is worth pointing out that",
	"to be honest",
	"to be fair",
	"to be clear",
	"to put it simply",
	"to put it another way",
	"long story short",
	"the thing is",
	"the fact is",
	"the point is",
	"basically what happened was",
	"essentially what happened was",
	"essentially",
	"basically",
	"generally speaking",
	"generally",
	"obviously",
	"clearly",
	"simply",
}
