package util

// StopWords is a set of common English stop words that carry little semantic meaning.
// Note: "error", "nil", "bug", "null" are intentionally excluded as they are meaningful in code context.
var StopWords = map[string]bool{
	"a": true, "about": true, "above": true, "after": true, "again": true,
	"against": true, "all": true, "also": true, "am": true, "an": true,
	"and": true, "any": true, "are": true, "as": true,
	"at": true, "be": true, "because": true, "been": true, "before": true,
	"being": true, "below": true, "between": true, "both": true, "but": true,
	"by": true, "can": true, "cannot": true, "could": true,
	"did": true, "do": true, "does": true,
	"doing": true, "down": true, "during": true,
	"each": true, "few": true, "for": true, "from": true, "further": true,
	"get": true, "got": true, "had": true, "has": true,
	"have": true, "having": true, "he": true,
	"her": true, "here": true,
	"hers": true, "herself": true, "him": true, "himself": true,
	"his": true, "how": true, "i": true,
	"if": true, "in": true,
	"into": true, "is": true, "it": true,
	"its": true, "itself": true, "just": true, "like": true,
	"may": true, "me": true, "more": true, "most": true,
	"my": true, "myself": true, "no": true, "nor": true, "not": true,
	"of": true, "off": true, "on": true, "once": true, "only": true,
	"or": true, "other": true, "ought": true, "our": true, "ours": true,
	"ourselves": true, "out": true, "over": true, "own": true, "same": true,
	"she":    true,
	"should": true, "so": true, "some": true, "such": true,
	"than": true, "that": true, "the": true, "their": true,
	"theirs": true, "them": true, "themselves": true, "then": true, "there": true,
	"these": true, "they": true,
	"this": true, "those": true, "through": true,
	"to": true, "too": true, "under": true, "until": true, "up": true,
	"very": true, "was": true, "we": true,
	"were": true, "what": true, "when": true, "where": true,
	"which": true, "while": true, "who": true,
	"whom": true, "why": true, "will": true, "with": true,
	"would": true, "you": true,
	"your": true, "yours": true,
	"yourself": true, "yourselves": true, "might": true,
	"shall": true, "upon": true, "within": true, "without": true,
	"among": true, "along": true, "around": true, "across": true,
	"behind": true, "beside": true, "besides": true, "beyond": true,
	"despite": true, "except": true, "inside": true, "outside": true,
	"since": true, "toward": true, "towards": true, "whether": true,
	"although": true, "though": true, "whereas": true, "whereby": true,
	"wherever": true, "whenever": true, "however": true, "whatever": true,
	"whoever": true, "whichever": true, "rather": true, "quite": true,
	"already": true, "always": true, "never": true, "often": true,
	"sometimes": true, "usually": true, "still": true, "yet": true,
	"even": true, "ever": true, "else": true, "much": true, "many": true,
	"little": true, "less": true, "least": true, "well": true, "back": true,
	"way": true, "now": true, "every": true, "either": true, "neither": true,
	"one": true, "two": true, "three": true, "first": true, "last": true,
	"next": true, "new": true, "old": true, "good": true, "great": true,
	"big": true, "small": true, "long": true, "short": true, "high": true,
	"low": true, "right": true, "left": true, "different": true, "another": true,
	"whole": true, "able": true, "need": true, "want": true, "make": true,
	"take": true, "come": true, "give": true, "know": true, "think": true,
	"look": true, "seem": true, "feel": true, "try": true, "ask": true,
	"work": true, "call": true, "keep": true, "let": true, "begin": true,
	"show": true, "hear": true, "play": true, "run": true, "move": true,
	"live": true, "believe": true, "hold": true, "bring": true, "happen": true,
	"write": true, "provide": true, "sit": true, "stand": true, "lose": true,
	"pay": true, "meet": true, "include": true, "continue": true, "set": true,
	"learn": true, "change": true, "lead": true, "understand": true, "watch": true,
	"follow": true, "stop": true, "create": true, "speak": true, "read": true,
	"spend": true, "grow": true, "open": true, "walk": true, "win": true,
	"offer": true, "remember": true, "love": true, "consider": true, "appear": true,
	"buy": true, "wait": true, "serve": true, "die": true, "send": true,
	"expect": true, "build": true, "stay": true, "fall": true, "cut": true,
	"reach": true, "kill": true, "remain": true, "suggest": true, "raise": true,
	"pass": true, "sell": true, "require": true, "report": true, "decide": true,
	"pull": true,
	// Common verb forms not already covered
	"looked": true, "discussed": true, "things": true, "talking": true,
	"using": true, "used": true, "said": true, "told": true, "went": true,
	"came": true, "took": true, "made": true, "put": true,
	"seen": true, "done": true, "known": true, "given": true, "found": true,
	"thought": true, "felt": true, "kept": true,
	"began": true, "shown": true, "heard": true, "ran": true, "brought": true,
	"written": true, "sat": true, "stood": true, "lost": true, "paid": true,
	"met": true, "included": true, "continued": true, "learned": true,
	"changed": true, "led": true, "understood": true, "watched": true,
	"followed": true, "stopped": true, "created": true, "spoke": true,
	"spent": true, "grew": true, "opened": true, "won": true,
	"offered": true, "remembered": true, "loved": true, "considered": true,
	"appeared": true, "bought": true, "waited": true, "served": true,
	"sent": true, "expected": true, "built": true, "stayed": true,
	"fell": true, "reached": true, "remained": true,
	"suggested": true, "raised": true, "passed": true, "sold": true,
	"required": true, "reported": true, "decided": true, "pulled": true,
	"thing": true, "stuff": true, "something": true, "anything": true,
	"everything": true, "nothing": true, "someone": true, "anyone": true,
	"everyone": true, "nobody": true, "everybody": true, "anybody": true,
	"somewhere": true, "anywhere": true, "everywhere": true, "nowhere": true,
	"somehow": true, "anyhow": true,
}
