package memory

import (
	"context"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mnemos-dev/mnemos/internal/domain"
	"github.com/mnemos-dev/mnemos/internal/embedding"
	"github.com/mnemos-dev/mnemos/internal/observe"
	"github.com/mnemos-dev/mnemos/internal/storage/markdown"
	sqlitestore "github.com/mnemos-dev/mnemos/internal/storage/sqlite"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// newManagerForSummarizeTest creates a Manager with no quality gate for summarization tests.
func newManagerForSummarizeTest(t *testing.T) *Manager {
	t.Helper()
	db, err := sqlitestore.Open(":memory:")
	require.NoError(t, err)

	store := sqlitestore.NewSQLiteStore(db)
	embedStore := sqlitestore.NewEmbeddingStore(db)
	embedder := embedding.NewNoopProvider(384)
	mir := markdown.NewMirror(t.TempDir(), false)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelError}))

	m := NewManager(store, embedStore, embedder, mir, 0.85, 0.92, logger, nil)
	t.Cleanup(func() {
		m.Stop()
		db.Close()
	})
	return m
}

// TestManagerSummarize_StoreEmptySummaryAutoGenerated verifies that storing content with
// no summary causes ExtractSummary to populate mem.Summary.
func TestManagerSummarize_StoreEmptySummaryAutoGenerated(t *testing.T) {
	m := newManagerForSummarizeTest(t)
	ctx := context.Background()

	// Content with >10 words so ExtractSummary returns non-empty
	content := "The SessionStore uses a sync.RWMutex to protect concurrent access in auth/session.go and prevents race conditions."
	result, err := m.Store(ctx, &domain.StoreRequest{
		Content:   content,
		ProjectID: "proj1",
	})
	require.NoError(t, err)
	require.NotNil(t, result)
	assert.True(t, result.Created)
	assert.NotEmpty(t, result.Memory.Summary, "summary should be auto-generated when req.Summary is empty")
}

func TestManagerSummarize_StoreEmptySummaryEmitsFeature(t *testing.T) {
	featuresLog := filepath.Join(t.TempDir(), "features.log")
	observe.SetLogPath(featuresLog)
	t.Cleanup(func() { observe.SetLogPath("") })

	m := newManagerForSummarizeTest(t)
	ctx := context.Background()

	content := "The SessionStore uses a sync.RWMutex to protect concurrent access in auth/session.go and prevents race conditions."
	_, err := m.Store(ctx, &domain.StoreRequest{
		Content:   content,
		ProjectID: "proj1",
	})
	require.NoError(t, err)

	data, err := os.ReadFile(featuresLog)
	require.NoError(t, err)
	log := string(data)
	assert.Contains(t, log, "\tsummarize\t")
	assert.Contains(t, log, "method=extractive")
	assert.Contains(t, log, "project_id=proj1")
}

func TestManagerSummarize_ShortContentDoesNotEmitFeature(t *testing.T) {
	featuresLog := filepath.Join(t.TempDir(), "features.log")
	observe.SetLogPath(featuresLog)
	t.Cleanup(func() { observe.SetLogPath("") })

	m := newManagerForSummarizeTest(t)
	ctx := context.Background()

	_, err := m.Store(ctx, &domain.StoreRequest{
		Content:   "Too short to summarize.",
		ProjectID: "proj1",
	})
	require.NoError(t, err)

	data, err := os.ReadFile(featuresLog)
	if os.IsNotExist(err) {
		return
	}
	require.NoError(t, err)
	assert.False(t, strings.Contains(string(data), "\tsummarize\t"))
}

// TestManagerSummarize_StoreExplicitSummaryPreserved verifies that a caller-provided
// summary is not overwritten by auto-generation.
func TestManagerSummarize_StoreExplicitSummaryPreserved(t *testing.T) {
	m := newManagerForSummarizeTest(t)
	ctx := context.Background()

	content := "The SessionStore uses a sync.RWMutex to protect concurrent access in auth/session.go and prevents race conditions."
	result, err := m.Store(ctx, &domain.StoreRequest{
		Content:   content,
		Summary:   "my summary",
		ProjectID: "proj1",
	})
	require.NoError(t, err)
	require.NotNil(t, result)
	assert.True(t, result.Created)
	assert.Equal(t, "my summary", result.Memory.Summary, "caller-provided summary should be preserved")
}

// TestManagerSummarize_UpdateContentChangeRegeneratesSummary verifies that updating
// a memory's content (with no explicit summary) regenerates the summary.
func TestManagerSummarize_UpdateContentChangeRegeneratesSummary(t *testing.T) {
	m := newManagerForSummarizeTest(t)
	ctx := context.Background()

	// Store initial memory
	initial := "The SessionStore uses a sync.RWMutex to protect concurrent access in auth/session.go and prevents race conditions."
	result, err := m.Store(ctx, &domain.StoreRequest{
		Content:   initial,
		ProjectID: "proj1",
	})
	require.NoError(t, err)
	require.True(t, result.Created)
	originalSummary := result.Memory.Summary

	// Update with new content (>10 words), no explicit summary
	newContent := "The EmbeddingStore caches vectors in a local SQLite database to avoid redundant API calls and reduce latency significantly."
	updated, err := m.Update(ctx, &domain.UpdateRequest{
		ID:      result.Memory.ID,
		Content: &newContent,
	})
	require.NoError(t, err)
	require.NotNil(t, updated)
	assert.NotEmpty(t, updated.Summary, "summary should be regenerated after content change")
	assert.NotEqual(t, originalSummary, updated.Summary, "summary should differ from original after content change")
}

// TestManagerSummarize_UpdateExplicitSummaryNotOverwritten verifies that when an update
// provides both new content and an explicit summary, the explicit summary wins.
func TestManagerSummarize_UpdateExplicitSummaryNotOverwritten(t *testing.T) {
	m := newManagerForSummarizeTest(t)
	ctx := context.Background()

	// Store initial memory
	initial := "The SessionStore uses a sync.RWMutex to protect concurrent access in auth/session.go and prevents race conditions."
	result, err := m.Store(ctx, &domain.StoreRequest{
		Content:   initial,
		ProjectID: "proj1",
	})
	require.NoError(t, err)
	require.True(t, result.Created)

	// Update with new content AND explicit summary
	newContent := "The EmbeddingStore caches vectors in a local SQLite database to avoid redundant API calls and reduce latency significantly."
	explicitSummary := "keep this"
	updated, err := m.Update(ctx, &domain.UpdateRequest{
		ID:      result.Memory.ID,
		Content: &newContent,
		Summary: &explicitSummary,
	})
	require.NoError(t, err)
	require.NotNil(t, updated)
	assert.Equal(t, "keep this", updated.Summary, "explicit summary should not be overwritten by auto-generation")
}

func TestManagerSummarize_UpdateUsesNewType(t *testing.T) {
	m := newManagerForSummarizeTest(t)
	ctx := context.Background()

	result, err := m.Store(ctx, &domain.StoreRequest{
		Content:   "Initial architecture note contains enough words to generate a stable summary for later updates.",
		Type:      domain.MemoryTypeSemantic,
		ProjectID: "summary-type",
	})
	require.NoError(t, err)

	content := "Run deployment carefully. 1. Build the release artifact. 2. Verify checksums before publishing. Finish by recording the exact command."
	memType := domain.MemoryTypeSkill
	updated, err := m.Update(ctx, &domain.UpdateRequest{
		ID:      result.Memory.ID,
		Content: &content,
		Type:    &memType,
	})
	require.NoError(t, err)

	assert.Equal(t, memType, updated.Type)
	assert.Equal(t, ExtractSummary(content, memType, 30), updated.Summary)
}
